-- z-msg 结构（H2 2.x，测试与本地起步用）
-- 与 schema-mysql.sql 定义同一批表；列语义/索引取舍的注释只写在 MySQL 那份里，
-- 这里不重复（H2 在非 MySQL 兼容模式下不支持列内 COMMENT 语法）。
-- 表集合与索引集合的一致性由 SchemaParityTest 在测试期校验。
-- 类型差异：AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY，TEXT/LONGTEXT -> CLOB，DATETIME -> TIMESTAMP。

CREATE TABLE IF NOT EXISTS z_msg_message (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    msg_id       VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    msg_type     VARCHAR(32)  NOT NULL DEFAULT 'NOTICE',
    title        VARCHAR(255)          DEFAULT NULL,
    content      CLOB,
    link_url     VARCHAR(512)          DEFAULT NULL,
    is_read      TINYINT      NOT NULL DEFAULT 0,
    read_time    TIMESTAMP             DEFAULT NULL,
    priority     TINYINT      NOT NULL DEFAULT 0,
    pinned       TINYINT      NOT NULL DEFAULT 0,
    dedup_key    VARCHAR(128)          DEFAULT NULL,
    expire_at    TIMESTAMP             DEFAULT NULL,
    deleted      TINYINT      NOT NULL DEFAULT 0,
    tenant_code  VARCHAR(64)           DEFAULT NULL,
    domain_code  VARCHAR(64)           DEFAULT NULL,
    created_time TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_msg_user_dedup ON z_msg_message (user_id, dedup_key);
CREATE INDEX IF NOT EXISTS idx_msg_user_list ON z_msg_message (user_id, is_read, created_time);
CREATE INDEX IF NOT EXISTS idx_msg_user_pinned ON z_msg_message (user_id, pinned, created_time);
CREATE INDEX IF NOT EXISTS idx_msg_msgid ON z_msg_message (msg_id);
CREATE INDEX IF NOT EXISTS idx_msg_expire ON z_msg_message (expire_at);

CREATE TABLE IF NOT EXISTS z_msg_template (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    biz_type     VARCHAR(64)  NOT NULL,
    channel      VARCHAR(32)  NOT NULL,
    subject      VARCHAR(255)          DEFAULT NULL,
    content      CLOB,
    status       TINYINT      NOT NULL DEFAULT 0,
    version      INT          NOT NULL DEFAULT 1,
    tenant_code  VARCHAR(64)  NOT NULL DEFAULT '',
    domain_code  VARCHAR(64)           DEFAULT NULL,
    created_time TIMESTAMP    NOT NULL,
    updated_time TIMESTAMP    NOT NULL,
    created_by   VARCHAR(64)           DEFAULT NULL,
    updated_by   VARCHAR(64)           DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpl_biz_channel ON z_msg_template (biz_type, channel, tenant_code);

CREATE TABLE IF NOT EXISTS z_msg_template_i18n (
    id           BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_id  BIGINT      NOT NULL,
    locale       VARCHAR(16) NOT NULL,
    subject      VARCHAR(255)         DEFAULT NULL,
    content      CLOB,
    created_time TIMESTAMP   NOT NULL,
    updated_time TIMESTAMP   NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpl_i18n ON z_msg_template_i18n (template_id, locale);

CREATE TABLE IF NOT EXISTS z_msg_template_version (
    id           BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_id  BIGINT   NOT NULL,
    version      INT      NOT NULL,
    subject      VARCHAR(255)    DEFAULT NULL,
    content      CLOB,
    change_note  VARCHAR(255)    DEFAULT NULL,
    created_time TIMESTAMP NOT NULL,
    created_by   VARCHAR(64)     DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpl_ver ON z_msg_template_version (template_id, version);

CREATE TABLE IF NOT EXISTS z_msg_delivery_log (
    id                  BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    biz_type            VARCHAR(64)          DEFAULT NULL,
    channel             VARCHAR(32) NOT NULL,
    provider            VARCHAR(32) NOT NULL,
    receiver            VARCHAR(128)         DEFAULT NULL,
    user_id             BIGINT               DEFAULT NULL,
    template_id         BIGINT               DEFAULT NULL,
    rendered_subject    VARCHAR(255)         DEFAULT NULL,
    rendered_content    CLOB,
    provider_message_id VARCHAR(128)         DEFAULT NULL,
    status              TINYINT     NOT NULL DEFAULT 0,
    error_code          VARCHAR(64)          DEFAULT NULL,
    error_message       VARCHAR(512)         DEFAULT NULL,
    retry_count         INT         NOT NULL DEFAULT 0,
    max_retry           INT         NOT NULL DEFAULT 0,
    next_retry_time     TIMESTAMP            DEFAULT NULL,
    duration_ms         INT                  DEFAULT NULL,
    tenant_code         VARCHAR(64)          DEFAULT NULL,
    domain_code         VARCHAR(64)          DEFAULT NULL,
    created_time        TIMESTAMP   NOT NULL,
    updated_time        TIMESTAMP   NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_log_biz_time ON z_msg_delivery_log (biz_type, created_time);
CREATE INDEX IF NOT EXISTS idx_log_user_time ON z_msg_delivery_log (user_id, created_time);
CREATE INDEX IF NOT EXISTS idx_log_status_time ON z_msg_delivery_log (status, created_time);
CREATE INDEX IF NOT EXISTS idx_log_retry ON z_msg_delivery_log (status, next_retry_time);
CREATE INDEX IF NOT EXISTS idx_log_provider_msg ON z_msg_delivery_log (provider_message_id);

CREATE TABLE IF NOT EXISTS z_msg_batch_task (
    id             BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    biz_type       VARCHAR(64) NOT NULL,
    channel        VARCHAR(32) NOT NULL,
    template_id    BIGINT               DEFAULT NULL,
    total_count    INT         NOT NULL DEFAULT 0,
    success_count  INT         NOT NULL DEFAULT 0,
    failed_count   INT         NOT NULL DEFAULT 0,
    status         TINYINT     NOT NULL DEFAULT 0,
    params_json    CLOB,
    receivers_json CLOB,
    error_message  VARCHAR(512)         DEFAULT NULL,
    tenant_code    VARCHAR(64)          DEFAULT NULL,
    domain_code    VARCHAR(64)          DEFAULT NULL,
    created_time   TIMESTAMP   NOT NULL,
    updated_time   TIMESTAMP   NOT NULL,
    created_by     VARCHAR(64)          DEFAULT NULL,
    finished_time  TIMESTAMP            DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_batch_status_time ON z_msg_batch_task (status, created_time);
CREATE INDEX IF NOT EXISTS idx_batch_biz_time ON z_msg_batch_task (biz_type, created_time);

CREATE TABLE IF NOT EXISTS z_msg_user_preference (
    id           BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT      NOT NULL,
    biz_type     VARCHAR(64) NOT NULL,
    channels     VARCHAR(255)         DEFAULT NULL,
    quiet_start  VARCHAR(8)           DEFAULT NULL,
    quiet_end    VARCHAR(8)           DEFAULT NULL,
    tenant_code  VARCHAR(64) NOT NULL DEFAULT '',
    domain_code  VARCHAR(64)          DEFAULT NULL,
    created_time TIMESTAMP   NOT NULL,
    updated_time TIMESTAMP   NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pref_user_biz ON z_msg_user_preference (user_id, biz_type, tenant_code);
